default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format check
        entry: uv run ruff format --check --force-exclude
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types_or: [python, pyi]
